// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------------- //
// amt232_16b_falling_sample //
// ------------------------- //

#define amt232_16b_falling_sample_wrap_target 0
#define amt232_16b_falling_sample_wrap 5
#define amt232_16b_falling_sample_pio_version 0

static const uint16_t amt232_16b_falling_sample_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0xe02f, //  1: set    x, 15           side 0
    0xb042, //  2: nop                    side 1
    0x4001, //  3: in     pins, 1         side 0
    0x0042, //  4: jmp    x--, 2          side 0
    0x8020, //  5: push   block           side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program amt232_16b_falling_sample_program = {
    .instructions = amt232_16b_falling_sample_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = amt232_16b_falling_sample_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config amt232_16b_falling_sample_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + amt232_16b_falling_sample_wrap_target, offset + amt232_16b_falling_sample_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

